---
- name: Install requirement python package.
  pip:
    name: '{{ orchestrator_python_dependent_packages }}'
    state: 'forcereinstall'
    extra_args: '--default-timeout=120 --ignore-installed -i https://{{ orchestrator_pypi_url }}/simple --trusted-host {{ orchestrator_pypi_url }}'
  register: orchestrator_python_status
  until: orchestrator_python_status is succeeded
  retries: 5
  delay: 2

- name: Check private key exists.
  stat:
    path: '{{ orchestrator_cert_path }}/server.key'
  register: check_cert_keys

- name: Certificate Signing operation.
  block:
    - name: Creating Certificate folder.
      file:
        dest: '{{ orchestrator_cert_path }}'
        state: 'directory'
        owner: 'root'
        mode: '1750'
    - name: Selfsigned CA file transfer.
      copy:
        src: 'ssl/{{ item }}'
        dest: '{{ orchestrator_cert_path }}/{{ item }}'
        owner: 'root'
        mode: '640'
      loop:
        - 'ca-cert.pem'
        - 'ca-key.pem'
    - name: Generate an OpenSSL private key.
      openssl_privatekey:
        path: '{{ orchestrator_cert_path }}/server.key'
        select_crypto_backend: 'cryptography'
        size: '4096'
        type: 'RSA'
        owner: 'root'
        mode: '0644'
        state: 'present'
    - name: Generate an OpenSSL Certificate Signing Request.
      openssl_csr:
        path: '{{ orchestrator_cert_path }}/server.csr'
        privatekey_path: '{{ orchestrator_cert_path }}/server.key'
        select_crypto_backend: 'cryptography'
        common_name: '{{ ansible_default_ipv4.address }}'
        subject_alt_name:
          - 'DNS:{{ ansible_hostname }}'
          - 'DNS:{{ ansible_fqdn }}'
          - 'IP:{{ ansible_default_ipv4.address }}'
        owner: 'root'
        mode: '0644'
        state: 'present'
    - name: Generate an OpenSSL certificate signed with your own CA certificate.
      openssl_certificate:
        path: '{{ orchestrator_cert_path }}/server.crt'
        csr_path: '{{ orchestrator_cert_path }}/server.csr'
        ownca_path: '{{ orchestrator_cert_path }}/ca-cert.pem'
        ownca_privatekey_path: '{{ orchestrator_cert_path }}/ca-key.pem'
        select_crypto_backend: 'cryptography'
        ownca_not_after: '+7305d'
        provider: 'ownca'
        owner: 'root'
        mode: '0644'
        state: 'present'
  when: not check_cert_keys.stat.exists or check_cert_keys.stat.size == 0
