---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution_file_variety }}.yml"

- name: Install the orchestrator dependencies packages.
  yum:
    name: "{{ orchestrator_dependent_packages }}"
    state: "present"
    validate_certs: "no"
    disable_gpg_check: "yes"
    update_cache: "yes"
  register: yum_status
  until: yum_status is succeeded
  retries: 5
  delay: 2
